# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/papers',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/papers',
                'lib_path': 'papers'},
  'syms': {'papers.core': {'papers.core.foo': ('core.html#foo', 'papers/core.py')}}}